language: android
sudo: false
env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - tools
before_install:
    - touch $HOME/.android/repositories.cfg
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "build-tools;28.0.3"
script:
    - echo "starting script"
    - ./gradlew clean build

# Emulator Management: Create, Start and Wait
before_script:
    - echo "Starting emulator"
    - echo no | android create avd --force -n test -t android-27 --abi armeabi-v7a -c 100M
    - emulator -avd test -no-window -skin 768x1280 &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &