language: android
sudo: false
env:
  global:
   - ANDROID_API_LEVEL=28
   - EMULATOR_API_LEVEL=27
   - ANDROID_BUILD_TOOLS_VERSION=28.0.3
   - ADB_INSTALL_TIMEOUT=20
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - sys-img-x86-android-26-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
  before_script:
    - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &